// Code generated by github.com/acexy/gen (base on gorm.io/gen). DO NOT EDIT.

package model

import "github.com/golang-acexy/starter-gorm/gormstarter"

const TableNameDemoTeacher = "demo_teacher"

// DemoTeacher 教师表
type DemoTeacher struct {
	ID         gormstarter.BaseModel[uint64] `json:"id"`
	CreateTime gormstarter.Timestamp         `json:"create_time"` // 创建时间
	UpdateTime gormstarter.Timestamp         `json:"update_time"` // 更新时间
	Name       string                        `json:"name"`        // 姓名
	Sex        string                        `json:"sex"`         // 性别
	Age        int32                         `json:"age"`         // 年龄
	ClassNo    string                        `json:"class_no"`    // 班级编号
}
