// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/golang-acexy/starter-gorm/gormstarter"

const TableNameDemoTeacher = "demo_teacher"

// DemoTeacher mapped from table <demo_teacher>
type DemoTeacher struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime gormstarter.Timestamp `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime gormstarter.Timestamp `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	Name       string                `gorm:"column:name;not null" json:"name"`
	Sex        string                `gorm:"column:sex;not null;default:1" json:"sex"`
	Age        int32                 `gorm:"column:age;not null" json:"age"`
	ClassNo    string                `gorm:"column:class_no;comment:班级编号" json:"class_no"` // 班级编号
}

// TableName DemoTeacher's table name
func (*DemoTeacher) TableName() string {
	return TableNameDemoTeacher
}
