// Code generated by github.com/acexy/gen (base on gorm.io/gen). DO NOT EDIT.

package model

import "github.com/golang-acexy/starter-gorm/gormstarter"

const TableNameStudent = "demo_student"

// Student mapped from table <demo_student>
type Student struct {
	ID         gormstarter.BaseModel[uint64] `json:"id"`
	CreateTime gormstarter.Timestamp         `json:"createTime"`
	UpdateTime gormstarter.Timestamp         `json:"updateTime"`
	Name       string                        `json:"name"`
	Sex        string                        `json:"sex"`
	Age        int32                         `json:"age"`
	TeacherID  int64                         `json:"teacherId"`
}

func (Student) TableName() string {
	return TableNameStudent
}
func (Student) DBType() gormstarter.DBType {
    return gormstarter.DBTypeMySQL
}